
services:
  app: # PHP-FPM (Laravel実行)
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:cached
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db

  web: # Nginx
    image: nginx:1.27-alpine
    container_name: laravel-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:  # MySQL 8
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: